### ISSUE TITLE
Set-VMSwitch : Failed while adding virtual Ethernet switch connections

### ISSUE THREAD

**Issue by maphew** [pawelgnatowski/WSL2-Network-Fix#9]
Now that I've managed to fix or work around the first batch of errors I'm stuck on this persistent one: 
~~~
Set-VMSwitch : Failed while adding virtual Ethernet switch connections.
Ethernet port '{EC88F1CA-81FD-421B-A395-FD47CD3BD45F}' bind failed: Element not found. (0x80070490).
At C:\Users\mhwilkie\code\WSL2-Network-Fix\resetWindowsNet.ps1:75 char:9
+         Set-VMSwitch WSL -NetAdapterName $active[0].Name ;
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (:) [Set-VMSwitch], VirtualizationException
    + FullyQualifiedErrorId : ObjectNotFound,Microsoft.HyperV.PowerShell.Commands.SetVMSwitch
~~~

I see threads here and there that indicate this might be particular to Wi-Fi adapters and Hyper-V.

**Comment by pawelgnatowski** [comment]
Interesting. Do i get this right - if you provide your wifi adapter name it fails either way?

**Comment by maphew** [comment]
Yes that's right it fails with wifi adapter name also. There are two failure messages depending on what initial state I'm in, one with _Element_ not found and this one is _Object_ not found. I'm not clear yet on the differences between the initial state, beyond that the Object not found one is the cleanest, e.g. after running `netcfg -d` (see the `troubleshooting-mhw.md` I just added to my testing branch).

~~~
Set-VMSwitch : Failed while adding virtual Ethernet switch connections.
Ethernet port '{EC88F1CA-81FD-421B-A395-FD47CD3BD45F}' bind failed: Element not found. (0x80070490).

Set-VMSwitch : Adding ports to the switch 'WSL' failed.                                             
The operation failed because the object was not found.  
~~~

**Comment by maphew** [comment]
Sounds similar: https://docs.microsoft.com/en-us/answers/questions/346843/hyper-v-virtual-switch-keeps-choosing-the-inactive.htm
